export const GET_ACCOUNT_BALANCE = "GET_ACCOUNT_BALANCE";
export const CREATE_BENEFICIARY = "CREATE_BENEFICIARY";
export const GET_BENEFICIARIES = "GET_BENEFICIARIES";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
