export const GET_ACCOUNT_BALANCE = "GET_ACCOUNT_BALANCE";
export const CREATE_BENEFICIARY = "CREATE_BENEFICIARY";
export const GET_BENEFICIARIES = "GET_BENEFICIARIES";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const REQUEST_CHEQUE_BOOK = "REQUEST_CHEQUE_BOOK";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const TRANSACTIONS_RECEIVED = "TRANSACTIONS_RECEIVED";
